### ISSUE TITLE
SDG Indicator 15.4.2 (BETA) Earth Engine Task Error 

### ISSUE THREAD

**Issue by sszzpruebas** [sepal-contrib/sepal_mgci#57]
Hi SEPAL team! :) 
I'm testing the SDG Indicator using SEPAL and GEE, but.. when i try to export subindicators A and B: 
<img width="924" alt="Start_SDG" src="https://github.com/sepal-contrib/sepal_mgci/assets/156904858/0f077b2b-c415-4f81-80f0-23302fde4502">
I receive the next error message in GEE:
<img width="371" alt="Error_SDG" src="https://github.com/sepal-contrib/sepal_mgci/assets/156904858/7f53525e-9b1c-4ce2-9a56-57a76e8d3578">

Where SEPAL try to save the file? (Asset, Storage, or Drive) 
It is possible to change the output location of the file? (to avoid this problem) 

Thank you in advance, 
Best regards,
Sylwer

**Comment by sszzpruebas** [comment]
Hi! :) 
Ok, this is the first screenshot:
![image](https://github.com/sepal-contrib/sepal_mgci/assets/156904858/99ca7b3c-0328-4069-8aa0-d98dadfe1a5c)

And this is the second one (When I disconnect from GEE):
 
![image](https://github.com/sepal-contrib/sepal_mgci/assets/156904858/91ffc562-0138-41d2-985a-66de0cd01413)

But if SDG export results by default to Drive, I think that there is the problem because my GEE account  don´t have access to Drive. I will try to solve it.

Thanks,
Best Regards, 

Sylwer

**Comment by dfguerrerom** [comment]
What do you mean with your GEE account doesn't have access to GDrive? when you link Google with SEPAL, it will return some credentials that allow the interaction with GEE and Drive. The tool is using this credentials to retrieve your files in the sepal environment. Do you have an specific configuration or something?

**Comment by sszzpruebas** [comment]
Yes, this account is associated with a GCP that includes multiple projects. Each user have acces to some project, it´s respective Storage (Buckets) and GEE project. In this case, Google Drive has a different administrator. I have contacted them, and I believe I will have permission soon. 
Thank you, 
Sylwer

**Comment by sszzpruebas** [comment]
Solved,
Finally, once I had obtained the permissions for my account to access Drive, the problem was resolved (as I mentioned before).
Thank you ;),
Sylwer
